# Copyright (C) 2025 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load(
    "@kleaf//build/kernel/kleaf:kernel.bzl",
    "ddk_module",
    "kernel_compile_commands",
)
load("@rules_python//python:defs.bzl", "py_binary")
load(":compdb_test.bzl", "compdb_test")

ddk_module(
    name = "module_1",
    srcs = [
        "empty.S",
        "module_1.c",
    ],
    out = "module.ko",
    kernel_build = "@kleaf//common:kernel_aarch64",
    local_defines = ["TEST"],
)

kernel_compile_commands(
    name = "module_1_compdb",
    deps = [":module_1"],
)

compdb_test(
    name = "module_1_flags_test",
    target = ":module_1_compdb",
    test_script = ":compdb_flags_test",
)

ddk_module(
    name = "module_2",
    srcs = [
        "subdir/empty.S",
        "subdir/module_2.c",
    ],
    out = "subdir/module.ko",
    includes = ["subdir"],
    kernel_build = "@kleaf//common:kernel_aarch64",
    local_defines = ["TEST"],
)

kernel_compile_commands(
    name = "module_2_compdb",
    deps = [":module_2"],
)

compdb_test(
    name = "module_2_flags_test",
    target = ":module_2_compdb",
    test_script = ":compdb_flags_test",
)

py_binary(
    name = "compdb_flags_test",
    srcs = ["compdb_flags_test.py"],
    deps = [
        "@io_abseil_py//absl/testing:absltest",
    ],
)

ddk_module(
    name = "overwrite_mod_a",
    srcs = ["overwrite_mod_a.c"],
    out = "overwrite_mod_a.ko",
    defconfig = "defconfig.overwrite_a",
    kconfig = "Kconfig.overwrite_a",
    kernel_build = "@kleaf//common:kernel_aarch64",
    tags = ["manual"],
    visibility = ["//visibility:private"],
)

ddk_module(
    name = "overwrite_mod_b",
    srcs = ["overwrite_mod_b.c"],
    out = "overwrite_mod_b.ko",
    defconfig = "defconfig.overwrite_b",
    kconfig = "Kconfig.overwrite_b",
    kernel_build = "@kleaf//common:kernel_aarch64",
    tags = ["manual"],
    visibility = ["//visibility:private"],
)

kernel_compile_commands(
    name = "overwrite_compdb",
    tags = ["manual"],
    deps = [
        ":overwrite_mod_a",
        ":overwrite_mod_b",
    ],
)

py_binary(
    name = "compdb_overwrite_test",
    srcs = ["compdb_overwrite_test.py"],
    deps = [
        "@io_abseil_py//absl/testing:absltest",
    ],
)

compdb_test(
    name = "compdb_overwrite_test_target",
    target = ":overwrite_compdb",
    test_script = ":compdb_overwrite_test",
)

test_suite(
    name = "compdb_test",
    tests = [
        # keep sorted
        ":compdb_overwrite_test_target",
        ":module_1_flags_test",
        ":module_2_flags_test",
    ],
)
