load(
    "//build/kernel/kleaf:kernel.bzl",
    "kernel_build",
)
load(":kleaf_test.bzl", "kleaf_test")

kernel_build(
    name = "test_kernel",
    srcs = [
        "//common:kernel_aarch64_sources",
    ],
    outs = ["fake.dtb"],
    arch = "arm64",
    base_kernel = "//common:kernel_aarch64",
    build_config = "build.config.kleaf_test",
    defconfig = "//common:arch/arm64/configs/gki_defconfig",
    dtstree = "//common-modules/virtual-device/kleaf_test/dts",
    kconfig_ext = "Kconfig.ext",
    make_goals = [
        "modules",
        "dtbs",
    ],
    makefile = "//common:Makefile",
    module_outs = [],
    post_defconfig_fragments = [
        "kleaf_test.fragment",
    ],
    visibility = [":__subpackages__"],
)

# Tests on Kleaf functionality using virtual device as a baseline.
kleaf_test(
    name = "kleaf_test",
    extras = [
        # keep sorted
        "//common-modules/virtual-device/kleaf_test/assembly_test",
        "//common-modules/virtual-device/kleaf_test/mixed_dep_test",
        "//common-modules/virtual-device/kleaf_test/rust_test",
    ],
    kernel_build = ":test_kernel",
)
